# Generated by Django 3.2.23 on 2023-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cargo', models.TextField()),
                ('load', models.TextField()),
                ('load_pn', models.TextField()),
                ('qty', models.TextField()),
                ('gw', models.TextField()),
                ('cbm', models.TextField()),
                ('size', models.TextField()),
                ('unload', models.TextField()),
                ('pic', models.TextField()),
                ('load_t', models.TextField()),
                ('transport', models.TextField()),
                ('vn', models.TextField()),
                ('transport_pn', models.TextField()),
            ],
        ),
    ]
