# Generated by Django 3.2.23 on 2023-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchlog', '0002_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(),
        ),
    ]
