# Generated by Django 3.2.23 on 2023-12-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchlog', '0004_monthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthdata',
            name='month',
            field=models.TextField(max_length=10),
        ),
    ]
